import { l10n } from 'vscode';

export const msg = {
  compiler: {
    alreadyCompiling: (file: string) => l10n.t('"{0}" já está sendo compilado.', file),
    compiling: (file: string) => l10n.t('Compilando: {0}', file),
    success: (file: string) => l10n.t('Compilação bem-sucedida: {0}', file),
    failed: (file: string) => l10n.t('Compilação falhou: {0}', file),
    notPawnFile: () => l10n.t('Abra um arquivo .pwn para compilar.'),
    noCompiler: () => l10n.t('Compilador não configurado. Use "PawnPro: Detectar compilador" ou configure em .pawnpro/config.json'),
    compilerNotFound: (path: string) => l10n.t('Falha ao iniciar pawncc: {0}', path),
    detecting: () => l10n.t('Detectando compilador...'),
    detected: (path: string) => l10n.t('pawncc detectado: {0}', path),
    notDetected: () => l10n.t('Compilador não detectado automaticamente.'),
  },

  server: {
    starting: () => l10n.t('Iniciando servidor...'),
    started: () => l10n.t('Servidor iniciado'),
    stopping: () => l10n.t('Parando servidor...'),
    stopped: () => l10n.t('Servidor parado'),
    restarting: () => l10n.t('Reiniciando servidor...'),
    notConfigured: () => l10n.t('Configure "server.path" em .pawnpro/config.json (executável do servidor).'),
    notFound: (path: string) => l10n.t('Servidor não encontrado: {0}', path),
    alreadyRunning: () => l10n.t('Servidor já está em execução.'),
    notRunning: () => l10n.t('Servidor não está em execução.'),
    failedStart: (err: string) => l10n.t('Falha ao iniciar servidor: {0}', err),
    rconFailed: (err: string) => l10n.t('Falha ao enviar RCON: {0}', err),
    rconInvalidPassword: () => l10n.t('Senha RCON vazia ou inválida ("changename"). Comando não enviado.'),
    rconHint: () => l10n.t('Envie apenas o comando, ex.: "gmx" ou "say oii".'),
  },

  themes: {
    schemeNotFound: (name: string) => l10n.t('[PawnPro] Esquema não encontrado: {0}', name),
    schemePicker: () => l10n.t('Escolha o esquema de sintaxe PawnPro'),
    schemeApplied: (name: string) => l10n.t('PawnPro: esquema aplicado: {0}', name),
    syntaxRestored: () => l10n.t('PawnPro: sintaxe restaurada (removidas regras PawnPro).'),
  },

  extension: {
    cacheCleaned: () => l10n.t('PawnPro: cache limpo.'),
    activationError: (err: string) => l10n.t('[PawnPro] Erro de ativação: {0}', err),
    sdkFileNotFound: (platform: string) => l10n.t('PawnPro: arquivo SDK ({0}) não encontrado. Configure "analysis.sdk.filePath" em .pawnpro/config.json.', platform),
  },

  naming: {
    noFilePath: () => l10n.t('PawnPro: caminho do arquivo de lista não configurado.'),
    migrateConfirm: (sizeMb: string) => l10n.t('As listas a migrar somam {0} MB, acima do limite configurado. Migrar mesmo assim?', sizeMb),
    migrateProceed: () => l10n.t('Migrar'),
    migratedBlocklist: (n: number) => l10n.t('{0} nome(s) proibido(s) → .ban', n),
    migratedLoopIndices: (n: number) => l10n.t('{0} índice(s) de loop → .allow', n),
    migrateDone: (summary: string) => l10n.t('PawnPro: migração concluída ({0}).', summary),
    migrateDoneBackup: (summary: string, path: string) => l10n.t('PawnPro: migração concluída ({0}). Backup dos itens em {1} — confira e apague quando quiser.', summary, path),
    migrateFailed: () => l10n.t('PawnPro: falha ao migrar as listas. O config.json não foi alterado.'),
    recoverNothing: () => l10n.t('PawnPro: nada a recuperar no config.json.'),
    recoverDone: (n: number) => l10n.t('PawnPro: {0} item(ns) movido(s) do config.json para os arquivos .ban/.allow.', n),
    recoverDoneBackup: (n: number, path: string) => l10n.t('PawnPro: {0} item(ns) movido(s) do config.json. Backup em {1} — confira e apague quando quiser.', n, path),
  },

  settings: {
    title: () => l10n.t('PawnPro — Configurações'),
    openSettings: () => l10n.t('Abrir Configurações PawnPro'),
    openSettingsDetail: () => l10n.t('Interface visual para todas as configurações do projeto'),

    noteText: () => l10n.t('Configurações de projeto ficam em .pawnpro/config.json (prioridade maior). Configurações globais em ~/.pawnpro/config.json valem para todos os projetos.'),

    navCompiler:  () => l10n.t('Compilador'),
    navIncludes:  () => l10n.t('Includes'),
    navBuild:     () => l10n.t('Build'),
    navAnalysis:  () => l10n.t('Análise'),
    navFormat:    () => l10n.t('Formatação'),
    navSyntax:    () => l10n.t('Sintaxe'),
    navInterface: () => l10n.t('Interface'),
    navServer:    () => l10n.t('Servidor'),

    compilerPath:        () => l10n.t('Caminho do compilador'),
    compilerPathDesc:    () => l10n.t('Caminho para o executável pawncc. Deixe vazio para usar a detecção automática.'),
    compilerAuto:        () => l10n.t('Detecção automática'),
    compilerAutoDesc:    () => l10n.t('Detecta o pawncc automaticamente nos caminhos padrão do projeto.'),
    compilerArgs:        () => l10n.t('Argumentos do compilador'),
    compilerArgsDesc:    () => l10n.t('Argumentos adicionais passados ao pawncc.'),

    includePaths:        () => l10n.t('Caminhos de include'),
    includePathsDesc:    () => l10n.t('Diretórios onde o compilador busca arquivos .inc. Use ${workspaceFolder} como variável.'),

    buildShowCommand:     () => l10n.t('Exibir comando'),
    buildShowCommandDesc: () => l10n.t('Mostra o comando de compilação completo no painel de saída antes de executar.'),
    outputEncoding:       () => l10n.t('Codificação de saída'),
    outputEncodingDesc:   () => l10n.t('Codificação usada para ler a saída do compilador.'),
    encodingWin1252:      () => l10n.t('Windows-1252 (padrão SA-MP)'),
    encodingUtf8:         () => l10n.t('UTF-8'),
    encodingLatin1:       () => l10n.t('Latin-1'),

    analysisWarnUnused:          () => l10n.t('Avisos em includes'),
    analysisWarnUnusedDesc:      () => l10n.t('Emite avisos de símbolos não utilizados também em arquivos .inc.'),
    analysisSuppressInc:         () => l10n.t('Silenciar diagnósticos em includes'),
    analysisSuppressIncDesc:     () => l10n.t('Arquivos .inc não exibem erros nem avisos.'),
    analysisSdkPlatform:         () => l10n.t('Plataforma SDK'),
    analysisSdkPlatformDesc:     () => l10n.t('omp: detecta qawno/include/open.mp.inc automaticamente. samp: configure o caminho abaixo. none: desativa suporte a SDK.'),
    analysisSdkPath:             () => l10n.t('Caminho do SDK'),
    analysisSdkPathDesc:         () => l10n.t('Arquivo .inc centralizador do SDK. Necessário apenas para SA-MP.'),
    sdkNone:                     () => l10n.t('Nenhum'),

    formatPreset:          () => l10n.t('Estilo de formatação'),
    formatPresetDesc:      () => l10n.t('Conjunto de regras aplicado ao formatar o código Pawn.'),
    formatPresetAllman:    () => l10n.t('Allman'),
    formatPresetKnr:       () => l10n.t('K&R'),
    formatPresetCompact:   () => l10n.t('Compacto'),
    formatPresetCustom:    () => l10n.t('Personalizado'),
    formatBraceStyle:      () => l10n.t('Posição da chave'),
    formatBraceStyleDesc:  () => l10n.t('Onde fica a chave de abertura de um bloco.'),
    formatBraceNextLine:   () => l10n.t('Linha própria'),
    formatBraceSameLine:   () => l10n.t('Mesma linha'),
    formatSpaceOps:        () => l10n.t('Espaço entre operadores'),
    formatSpaceOpsDesc:    () => l10n.t('Insere espaço em volta de operadores binários (a + b).'),
    formatEmptyBlock:      () => l10n.t('Bloco vazio na mesma linha'),
    formatEmptyBlockDesc:  () => l10n.t('Mantém blocos vazios colados ao controle (if (a) {}).'),
    formatPreserveArrayAlign:     () => l10n.t('Preservar alinhamento de arrays'),
    formatPreserveArrayAlignDesc: () => l10n.t('Mantém intacto o alinhamento manual em colunas de inicializadores de array { } em várias linhas.'),

    navNaming:             () => l10n.t('Nomenclatura'),
    namingEnabled:         () => l10n.t('Assistente de nomes'),
    namingEnabledDesc:     () => l10n.t('Avisa sobre nomes pobres (curtos, genéricos, fora do estilo). Desligado por padrão.'),
    namingMinLength:       () => l10n.t('Comprimento mínimo'),
    namingMinLengthDesc:   () => l10n.t('Sinaliza identificadores mais curtos que isto (índices de loop são tolerados).'),
    namingMaxFile:         () => l10n.t('Limite dos arquivos (MB)'),
    namingMaxFileDesc:     () => l10n.t('Tamanho máximo que a engine processa dos arquivos .ban/.allow. Não impede editá-los.'),
    namingBlocklist:       () => l10n.t('Nomes proibidos'),
    namingBlocklistDesc:   () => l10n.t('Lista de identificadores genéricos a evitar, num arquivo .ban editável.'),
    namingAllowShort:      () => l10n.t('Índices de loop curtos'),
    namingAllowShortDesc:  () => l10n.t('Nomes de uma letra tolerados em for, num arquivo .allow editável.'),
    namingOpenFile:        () => l10n.t('Abrir arquivo'),
    namingMigrate:         () => l10n.t('Migrar para arquivos'),
    namingMigrateNote:     () => l10n.t('Há listas de nomes salvas no formato antigo (no config.json).'),
    namingStyleGroup:      () => l10n.t('Estilos de nomenclatura por categoria'),
    namingStyleGroupDesc:  () => l10n.t('Convenções de caixa aceitas para cada tipo de identificador. Vazio = sem checagem.'),
    namingStyleFunctions:  () => l10n.t('Estilo de funções'),
    namingStyleGlobals:    () => l10n.t('Estilo de variáveis globais'),
    namingStyleLocals:     () => l10n.t('Estilo de variáveis locais'),
    namingStyleConstants:  () => l10n.t('Estilo de constantes (const, enum)'),
    namingStyleMacros:     () => l10n.t('Estilo de macros (#define)'),
    namingStyleParameters: () => l10n.t('Estilo de parâmetros'),

    syntaxScheme:          () => l10n.t('Esquema de cores'),
    syntaxSchemeDesc:      () => l10n.t('Esquema de realce de sintaxe aplicado aos arquivos Pawn.'),
    syntaxApplyOnStartup:  () => l10n.t('Aplicar ao iniciar'),
    syntaxApplyOnStartupDesc: () => l10n.t('Aplica automaticamente o esquema de sintaxe ao iniciar o editor.'),
    schemeAuto:            () => l10n.t('Automático'),
    schemeClassicLight:    () => l10n.t('Clássico (Claro)'),
    schemeModernLight:     () => l10n.t('Moderno (Claro)'),
    schemeClassicDark:     () => l10n.t('Clássico (Escuro)'),
    schemeModernDark:      () => l10n.t('Moderno (Escuro)'),
    schemeNone:            () => l10n.t('Nenhum'),

    uiShowIncludePaths:     () => l10n.t('Exibir caminhos na árvore de includes'),
    uiShowIncludePathsDesc: () => l10n.t('Mostra o caminho relativo de cada arquivo na árvore de includes da barra lateral.'),
    uiAnimateTitle:         () => l10n.t('Animar o título PawnPro'),
    uiAnimateTitleDesc:     () => l10n.t('Anima as letras do título no topo das páginas em sequência (teclado → bloco → cair), em loop com pausa. Desligado por padrão.'),
    uiLocale:               () => l10n.t('Idioma'),
    uiLocaleDesc:           () => l10n.t('Idioma dos diagnósticos e do debugger. Vazio segue o editor.'),
    localeAuto:             () => l10n.t('Automático'),
    localePtBr:             () => l10n.t('Português (Brasil)'),
    localeEn:               () => l10n.t('English'),

    serverType:         () => l10n.t('Tipo do servidor'),
    serverTypeDesc:     () => l10n.t('SA-MP, open.mp, ou detectar automaticamente pelo arquivo de configuração presente.'),
    serverPath:         () => l10n.t('Executável do servidor'),
    serverPathDesc:     () => l10n.t('Caminho para samp-server.exe ou omp-server. Vazio para detecção automática.'),
    serverCwd:          () => l10n.t('Diretório de trabalho'),
    serverCwdDesc:      () => l10n.t('Diretório onde o servidor é iniciado.'),
    serverArgs:         () => l10n.t('Argumentos do servidor'),
    serverArgsDesc:     () => l10n.t('Argumentos extras passados ao executável ao iniciar.'),
    serverClearOnStart: () => l10n.t('Limpar terminal ao iniciar'),
    serverClearOnStartDesc: () => l10n.t('Limpa o terminal antes de iniciar o servidor.'),
    serverFollowLog:    () => l10n.t('Acompanhamento do log'),
    serverFollowLogDesc: () => l10n.t('Quando rolar automaticamente o painel de log do servidor.'),
    serverLogPath:      () => l10n.t('Caminho do log'),
    serverLogPathDesc:  () => l10n.t('Arquivo de log do servidor a ser monitorado.'),
    serverLogEncoding:  () => l10n.t('Codificação do log'),
    serverLogEncodingDesc: () => l10n.t('Codificação do arquivo de log do servidor.'),
    followVisible:      () => l10n.t('Quando visível'),
    followAlways:       () => l10n.t('Sempre'),
    followOff:          () => l10n.t('Desativado'),
    serverTypeAuto:     () => l10n.t('Automático'),
    serverTypeSamp:     () => l10n.t('SA-MP'),
    serverTypeOmp:      () => l10n.t('open.mp'),

    btnAdd:    () => l10n.t('+ Adicionar'),
    btnRemove: () => l10n.t('Remover'),
  },

  statusBar: {
    tooltip: (mode: string) => l10n.t('PawnPro — {0}', mode),
    modeRust: () => l10n.t('Motor Rust LSP ativo'),
    menuTitle: () => l10n.t('PawnPro — Ações'),
    restartEngine: () => l10n.t('Reiniciar motor'),
    restartEngineDetail: () => l10n.t('Reinicia o servidor LSP e limpa o cache'),
    engineRestarted: () => l10n.t('PawnPro: motor reiniciado.'),
    configNotFound: () => l10n.t('Nenhum workspace aberto.'),
    sectionServer: () => l10n.t('Servidor'),
    serverStart: () => l10n.t('Iniciar servidor'),
    serverStop: () => l10n.t('Parar servidor'),
    serverRestart: () => l10n.t('Reiniciar servidor'),
    editServerCfg: () => l10n.t('Editar configuração do servidor'),
    editServerCfgDetail: () => l10n.t('Abre server.cfg (SA-MP) ou config.json (open.mp)'),
    serverCfgNotFound: (p: string) => l10n.t('Arquivo de configuração não encontrado em: {0}', p),
    sectionTemplates: () => l10n.t('Novo script'),
    newGamemode: () => l10n.t('Novo Gamemode'),
    newFilterscript: () => l10n.t('Novo Filterscript'),
    newInclude: () => l10n.t('Novo Include'),
    sectionHelp: () => l10n.t('Ajuda'),
    openHelp: () => l10n.t('Ajuda e informações'),
    openHelpDetail: () => l10n.t('Versões, links e guia do depurador'),
  },

  whatsNew: {
    panelTitle:   () => l10n.t('PawnPro — O que há de novo'),
    noChangelog:  () => l10n.t('Nenhum registro de mudanças encontrado para esta versão.'),
    reopenHint:   () => l10n.t('Use <code>PawnPro: O que há de novo</code> para reabrir.'),
  },

  help: {
    panelTitle:      () => l10n.t('PawnPro — Ajuda e informações'),
    subtitle:        () => l10n.t('Componentes, links e guia do depurador'),
    compilerTitle:   () => l10n.t('Compilador recomendado'),
    compilerBody:    () => l10n.t('Compile seus scripts com o **compilador do open.mp** — versão **3.10.11**, a única existente e a testada no momento. É o **único compilador testado** e o **recomendado**, tanto para a análise da engine quanto para a depuração. Outros compiladores podem gerar código ou informação de depuração incompatíveis.'),
    compilerLink:    () => l10n.t('Baixar o compilador do open.mp'),
    componentsTitle: () => l10n.t('Componentes'),
    extensionLabel:  () => l10n.t('Extensão PawnPro'),
    engineLabel:     () => l10n.t('Engine LSP (pawnpro-engine)'),
    debuggerLabel:   () => l10n.t('Adaptador do depurador (dap-adapter)'),
    linksTitle:      () => l10n.t('Links'),
    linkDocs:        () => l10n.t('Documentação'),
    linkExtension:   () => l10n.t('Repositório da extensão'),
    linkEngine:      () => l10n.t('Repositório da engine LSP'),
    linkDebugger:    () => l10n.t('Repositório do depurador'),
    linkIssues:      () => l10n.t('Reportar um problema'),
    debuggerTitle:   () => l10n.t('Depurador: instalar no servidor'),
    debuggerIntro:   () => l10n.t('O adaptador vem na extensão e inicia sozinho. A única etapa manual é instalar o **plugin do servidor** — uma vez por servidor. O mesmo binário serve **SA-MP** e **open.mp**.'),
    stepDownload:    () => l10n.t('**1. Baixe o plugin** na [release do PawnPro Debugger]({0}): `pawnpro_debug.so` (Linux) ou `pawnpro_debug.dll` (Windows). Não renomeie.'),
    stepInstallOmp:  () => l10n.t('**2a. open.mp** — copie o binário para a pasta `components/`. O servidor o descobre sozinho; nenhum registro é necessário.'),
    stepInstallSamp: () => l10n.t('**2b. SA-MP** — copie para `plugins/` e adicione `pawnpro_debug.so` à linha `plugins` do `server.cfg`.'),
    usageTitle:      () => l10n.t('Depurar'),
    usageBody:       () => l10n.t('Abra o gamemode (`.pwn`), clique na margem para colocar breakpoints e pressione **F5**. A extensão recompila com `-d3`, verifica o plugin, sobe o servidor e conecta. A saída aparece no **Console de Depuração**.'),
    fullGuide:       () => l10n.t('Guia completo do depurador'),
    reopenHint:      () => l10n.t('Use <code>PawnPro: Ajuda e informações</code> para reabrir.'),
  },

  store: {
    title:             () => l10n.t('Biblioteca de Recursos'),
    subtitle:          () => l10n.t('plugins, filterscripts e includes'),
    searchPlaceholder: () => l10n.t('Buscar pacotes…'),
    install:           () => l10n.t('Adicionar'),
    remove:            () => l10n.t('Remover'),
    added:             () => l10n.t('Adicionado'),
    filterAdded:       () => l10n.t('Adicionados'),
    back:              () => l10n.t('Voltar'),
    empty:             () => l10n.t('Nenhum pacote encontrado.'),
    emptyAdded:        () => l10n.t('Nenhum recurso adicionado a este projeto ainda.'),
    mockNote:          () => l10n.t('Prévia: catálogo de exemplo. Adicionar/remover ainda não altera o projeto.'),
    kindPlugin:        () => l10n.t('plugin'),
    kindFilterscript:  () => l10n.t('filterscript'),
    kindInclude:       () => l10n.t('include'),
    kindGamemode:      () => l10n.t('gamemode'),
    sourcePawnpro:     () => l10n.t('PawnPro'),
    sourceOpenmp:      () => l10n.t('open.mp'),
    byAuthor:          () => l10n.t('por'),
    installMock:       (name: string) => l10n.t('Adicionar "{0}" ao projeto ainda não está disponível (prévia).', name),
    removeMock:        (name: string) => l10n.t('Remover "{0}" do projeto ainda não está disponível (prévia).', name),
    installUnavailable:() => l10n.t('Adicionar/remover ainda não está disponível (prévia).'),
    filterAll:         () => l10n.t('Todos'),
    filterKind:        () => l10n.t('Tipo'),
    filterSource:      () => l10n.t('Fonte'),
    sortLabel:         () => l10n.t('Ordenar'),
    sortRelevance:     () => l10n.t('Relevância'),
    sortName:          () => l10n.t('Nome'),
    sortDownloads:     () => l10n.t('Downloads'),
    sortUpdated:       () => l10n.t('Atualização'),
    clearSearch:       () => l10n.t('Limpar'),
    resultCount:       (n: string) => l10n.t('{0} pacote(s)', n),
    secDescription:    () => l10n.t('Descrição'),
    secScreenshots:    () => l10n.t('Capturas de tela'),
    secDependencies:   () => l10n.t('Dependências'),
    secInfo:           () => l10n.t('Informações'),
    secLinks:          () => l10n.t('Links'),
    infoLicense:       () => l10n.t('Licença'),
    infoSize:          () => l10n.t('Tamanho'),
    infoDownloads:     () => l10n.t('Downloads'),
    infoUpdated:       () => l10n.t('Atualizado em'),
    infoVersion:       () => l10n.t('Versão'),
    linkRepository:    () => l10n.t('Repositório'),
    linkDocs:          () => l10n.t('Documentação'),
    noScreenshots:     () => l10n.t('Sem capturas de tela.'),
    noDependencies:    () => l10n.t('Nenhuma dependência.'),
    secUsage:          () => l10n.t('Instalar / usar'),
    usageInstall:      (name: string) => l10n.t('Instale "{0}" pela loja (em breve) ou manualmente.', name),
    usageInclude:      (name: string) => l10n.t('No seu script, adicione: #include <{0}>', name),
    usageDocs:         () => l10n.t('Consulte a documentação para a configuração completa.'),
    selectVersion:     () => l10n.t('Selecionar versão'),
  },

  debug: {
    defaultName:     () => l10n.t('Depurar script Pawn (PawnPro)'),
    noProgram:       () => l10n.t('Defina o caminho do `.amx` (campo "program") para depurar.'),
    adapterNotFound: () => l10n.t('Adaptador de depuração não encontrado. Compile/instale o PawnPro Debugger.'),
    compileFailed:   () => l10n.t('Falha ao compilar o script com informação de depuração. Verifique o painel de saída.'),
    serverNotFound:  () => l10n.t('Servidor não encontrado. Configure `server.path` ou deixe o executável na raiz do workspace.'),
    missingPluginFile: (p: string) => l10n.t('Instale o plugin de depuração em {0}.', p),
    pluginNameClash: (p: string) =>
      l10n.t('Há um arquivo em {0}, mas não é o plugin de depuração do PawnPro (nome em conflito). Substitua-o pelo plugin oficial.', p),
    missingPluginReg:  (kind: string) =>
      kind === 'samp'
        ? l10n.t('Adicione o plugin à linha `plugins` do server.cfg.')
        : l10n.t('Adicione o plugin a `pawn.legacy_plugins` no config.json (ou use a pasta components/).'),
    preflightFailed: (what: string) =>
      l10n.t('O servidor não parece pronto para depuração. {0} Iniciar mesmo assim?', what),
    btnStartAnyway:  () => l10n.t('Iniciar mesmo assim'),
    btnCancel:       () => l10n.t('Cancelar'),
  },

  templates: {
    selectVariant:    () => l10n.t('Selecione a variante'),
    selectType:       () => l10n.t('Selecione o tipo de script'),
    labelGmOmp:       () => l10n.t('Gamemode — open.mp'),
    labelGmSamp:      () => l10n.t('Gamemode — SA-MP'),
    labelFsOmp:       () => l10n.t('Filterscript — open.mp'),
    labelFsSamp:      () => l10n.t('Filterscript — SA-MP'),
    labelIncOmp:      () => l10n.t('Include — open.mp'),
    descGmOmp:        () => l10n.t('#include <open.mp>'),
    descGmSamp:       () => l10n.t('#include <a_samp>'),
    descFsOmp:        () => l10n.t('#include <open.mp>'),
    descFsSamp:       () => l10n.t('#include <a_samp>'),
    descIncOmp:       () => l10n.t('.inc para open.mp'),
  },
};
