import * as nls from 'vscode-nls';

const localize = nls.loadMessageBundle();

export const msg = {
  compiler: {
    alreadyCompiling: (file: string) => localize('compiler.alreadyCompiling', '"{0}" já está sendo compilado.', file),
    compiling: (file: string) => localize('compiler.compiling', 'Compilando: {0}', file),
    success: (file: string) => localize('compiler.success', 'Compilação bem-sucedida: {0}', file),
    failed: (file: string) => localize('compiler.failed', 'Compilação falhou: {0}', file),
    notPawnFile: () => localize('compiler.notPawnFile', 'Abra um arquivo .pwn para compilar.'),
    noCompiler: () => localize('compiler.noCompiler', 'Compilador não configurado. Use "PawnPro: Detectar compilador" ou configure em .pawnpro/config.json'),
    compilerNotFound: (path: string) => localize('compiler.compilerNotFound', 'Falha ao iniciar pawncc: {0}', path),
    detecting: () => localize('compiler.detecting', 'Detectando compilador...'),
    detected: (path: string) => localize('compiler.detected', 'pawncc detectado: {0}', path),
    notDetected: () => localize('compiler.notDetected', 'Compilador não detectado automaticamente.'),
  },

  server: {
    starting: () => localize('server.starting', 'Iniciando servidor...'),
    started: () => localize('server.started', 'Servidor iniciado'),
    stopping: () => localize('server.stopping', 'Parando servidor...'),
    stopped: () => localize('server.stopped', 'Servidor parado'),
    restarting: () => localize('server.restarting', 'Reiniciando servidor...'),
    notConfigured: () => localize('server.notConfigured', 'Configure "server.path" em .pawnpro/config.json (executável do servidor).'),
    notFound: (path: string) => localize('server.notFound', 'Servidor não encontrado: {0}', path),
    alreadyRunning: () => localize('server.alreadyRunning', 'Servidor já está em execução.'),
    notRunning: () => localize('server.notRunning', 'Servidor não está em execução.'),
    failedStart: (err: string) => localize('server.failedStart', 'Falha ao iniciar servidor: {0}', err),
    rconFailed: (err: string) => localize('server.rconFailed', 'Falha ao enviar RCON: {0}', err),
    rconInvalidPassword: () => localize('server.rconInvalidPassword', 'Senha RCON vazia ou inválida ("changename"). Comando não enviado.'),
    rconHint: () => localize('server.rconHint', 'Envie apenas o comando, ex.: "gmx" ou "say oii".'),
  },

  themes: {
    schemeNotFound: (name: string) => localize('themes.schemeNotFound', '[PawnPro] Esquema não encontrado: {0}', name),
    schemePicker: () => localize('themes.schemePicker', 'Escolha o esquema de sintaxe PawnPro'),
    schemeApplied: (name: string) => localize('themes.schemeApplied', 'PawnPro: esquema aplicado: {0}', name),
    syntaxRestored: () => localize('themes.syntaxRestored', 'PawnPro: sintaxe restaurada (removidas regras PawnPro).'),
  },

  extension: {
    cacheCleaned: () => localize('extension.cacheCleaned', 'PawnPro: cache limpo.'),
    activationError: (err: string) => localize('extension.activationError', '[PawnPro] Erro de ativação: {0}', err),
    sdkFileNotFound: (platform: string) => localize('extension.sdkFileNotFound', 'PawnPro: arquivo SDK ({0}) não encontrado. Configure "analysis.sdk.filePath" em .pawnpro/config.json.', platform),
  },

  settings: {
    title: () => localize('settings.title', 'PawnPro — Configurações'),
    openSettings: () => localize('settings.openSettings', 'Abrir Configurações PawnPro'),
    openSettingsDetail: () => localize('settings.openSettingsDetail', 'Interface visual para todas as configurações do projeto'),

    noteText: () => localize('settings.noteText', 'Configurações de projeto ficam em .pawnpro/config.json (prioridade maior). Configurações globais em ~/.pawnpro/config.json valem para todos os projetos.'),

    navCompiler:  () => localize('settings.nav.compiler', 'Compilador'),
    navIncludes:  () => localize('settings.nav.includes', 'Includes'),
    navBuild:     () => localize('settings.nav.build', 'Build'),
    navAnalysis:  () => localize('settings.nav.analysis', 'Análise'),
    navSyntax:    () => localize('settings.nav.syntax', 'Sintaxe'),
    navInterface: () => localize('settings.nav.interface', 'Interface'),
    navServer:    () => localize('settings.nav.server', 'Servidor'),

    compilerPath:        () => localize('settings.compiler.path', 'Caminho do compilador'),
    compilerPathDesc:    () => localize('settings.compiler.pathDesc', 'Caminho para o executável pawncc. Deixe vazio para usar a detecção automática.'),
    compilerAuto:        () => localize('settings.compiler.auto', 'Detecção automática'),
    compilerAutoDesc:    () => localize('settings.compiler.autoDesc', 'Detecta o pawncc automaticamente nos caminhos padrão do projeto.'),
    compilerArgs:        () => localize('settings.compiler.args', 'Argumentos do compilador'),
    compilerArgsDesc:    () => localize('settings.compiler.argsDesc', 'Argumentos adicionais passados ao pawncc.'),

    includePaths:        () => localize('settings.includes.paths', 'Caminhos de include'),
    includePathsDesc:    () => localize('settings.includes.pathsDesc', 'Diretórios onde o compilador busca arquivos .inc. Use ${workspaceFolder} como variável.'),

    buildShowCommand:     () => localize('settings.build.showCommand', 'Exibir comando'),
    buildShowCommandDesc: () => localize('settings.build.showCommandDesc', 'Mostra o comando de compilação completo no painel de saída antes de executar.'),
    outputEncoding:       () => localize('settings.build.encoding', 'Codificação de saída'),
    outputEncodingDesc:   () => localize('settings.build.encodingDesc', 'Codificação usada para ler a saída do compilador.'),
    encodingWin1252:      () => localize('settings.encoding.win1252', 'Windows-1252 (padrão SA-MP)'),
    encodingUtf8:         () => localize('settings.encoding.utf8', 'UTF-8'),
    encodingLatin1:       () => localize('settings.encoding.latin1', 'Latin-1'),

    analysisWarnUnused:          () => localize('settings.analysis.warnUnused', 'Avisos em includes'),
    analysisWarnUnusedDesc:      () => localize('settings.analysis.warnUnusedDesc', 'Emite avisos de símbolos não utilizados também em arquivos .inc.'),
    analysisSuppressInc:         () => localize('settings.analysis.suppressInc', 'Silenciar diagnósticos em includes'),
    analysisSuppressIncDesc:     () => localize('settings.analysis.suppressIncDesc', 'Arquivos .inc não exibem erros nem avisos.'),
    analysisSdkPlatform:         () => localize('settings.analysis.sdkPlatform', 'Plataforma SDK'),
    analysisSdkPlatformDesc:     () => localize('settings.analysis.sdkPlatformDesc', 'omp: detecta qawno/include/open.mp.inc automaticamente. samp: configure o caminho abaixo. none: desativa suporte a SDK.'),
    analysisSdkPath:             () => localize('settings.analysis.sdkPath', 'Caminho do SDK'),
    analysisSdkPathDesc:         () => localize('settings.analysis.sdkPathDesc', 'Arquivo .inc centralizador do SDK. Necessário apenas para SA-MP.'),
    sdkNone:                     () => localize('settings.sdk.none', 'Nenhum'),

    syntaxScheme:          () => localize('settings.syntax.scheme', 'Esquema de cores'),
    syntaxSchemeDesc:      () => localize('settings.syntax.schemeDesc', 'Esquema de realce de sintaxe aplicado aos arquivos Pawn.'),
    syntaxApplyOnStartup:  () => localize('settings.syntax.applyOnStartup', 'Aplicar ao iniciar'),
    syntaxApplyOnStartupDesc: () => localize('settings.syntax.applyOnStartupDesc', 'Aplica automaticamente o esquema de sintaxe ao iniciar o editor.'),
    schemeAuto:            () => localize('settings.scheme.auto', 'Automático'),
    schemeClassicLight:    () => localize('settings.scheme.classicLight', 'Clássico (Claro)'),
    schemeModernLight:     () => localize('settings.scheme.modernLight', 'Moderno (Claro)'),
    schemeClassicDark:     () => localize('settings.scheme.classicDark', 'Clássico (Escuro)'),
    schemeModernDark:      () => localize('settings.scheme.modernDark', 'Moderno (Escuro)'),
    schemeNone:            () => localize('settings.scheme.none', 'Nenhum'),

    uiShowIncludePaths:     () => localize('settings.ui.showIncludePaths', 'Exibir caminhos na árvore de includes'),
    uiShowIncludePathsDesc: () => localize('settings.ui.showIncludePathsDesc', 'Mostra o caminho relativo de cada arquivo na árvore de includes da barra lateral.'),
    uiLocale:               () => localize('settings.ui.locale', 'Idioma da engine'),
    uiLocaleDesc:           () => localize('settings.ui.localeDesc', 'Idioma das mensagens de diagnóstico. Vazio detecta automaticamente pelo idioma do editor.'),
    localeAuto:             () => localize('settings.locale.auto', 'Automático'),
    localePtBr:             () => localize('settings.locale.ptBr', 'Português (Brasil)'),
    localeEn:               () => localize('settings.locale.en', 'English'),

    serverType:         () => localize('settings.server.type', 'Tipo do servidor'),
    serverTypeDesc:     () => localize('settings.server.typeDesc', 'SA-MP, open.mp, ou detectar automaticamente pelo arquivo de configuração presente.'),
    serverPath:         () => localize('settings.server.path', 'Executável do servidor'),
    serverPathDesc:     () => localize('settings.server.pathDesc', 'Caminho para samp-server.exe ou omp-server. Vazio para detecção automática.'),
    serverCwd:          () => localize('settings.server.cwd', 'Diretório de trabalho'),
    serverCwdDesc:      () => localize('settings.server.cwdDesc', 'Diretório onde o servidor é iniciado.'),
    serverArgs:         () => localize('settings.server.args', 'Argumentos do servidor'),
    serverArgsDesc:     () => localize('settings.server.argsDesc', 'Argumentos extras passados ao executável ao iniciar.'),
    serverClearOnStart: () => localize('settings.server.clearOnStart', 'Limpar terminal ao iniciar'),
    serverClearOnStartDesc: () => localize('settings.server.clearOnStartDesc', 'Limpa o terminal antes de iniciar o servidor.'),
    serverFollowLog:    () => localize('settings.server.followLog', 'Acompanhamento do log'),
    serverFollowLogDesc: () => localize('settings.server.followLogDesc', 'Quando rolar automaticamente o painel de log do servidor.'),
    serverLogPath:      () => localize('settings.server.logPath', 'Caminho do log'),
    serverLogPathDesc:  () => localize('settings.server.logPathDesc', 'Arquivo de log do servidor a ser monitorado.'),
    serverLogEncoding:  () => localize('settings.server.logEncoding', 'Codificação do log'),
    serverLogEncodingDesc: () => localize('settings.server.logEncodingDesc', 'Codificação do arquivo de log do servidor.'),
    followVisible:      () => localize('settings.follow.visible', 'Quando visível'),
    followAlways:       () => localize('settings.follow.always', 'Sempre'),
    followOff:          () => localize('settings.follow.off', 'Desativado'),
    serverTypeAuto:     () => localize('settings.serverType.auto', 'Automático'),
    serverTypeSamp:     () => localize('settings.serverType.samp', 'SA-MP'),
    serverTypeOmp:      () => localize('settings.serverType.omp', 'open.mp'),

    btnAdd:    () => localize('settings.btn.add', '+ Adicionar'),
    btnRemove: () => localize('settings.btn.remove', 'Remover'),
  },

  statusBar: {
    tooltip: (mode: string) => localize('statusBar.tooltip', 'PawnPro — {0}', mode),
    modeRust: () => localize('statusBar.modeRust', 'Motor Rust LSP ativo'),
    menuTitle: () => localize('statusBar.menuTitle', 'PawnPro — Ações'),
    restartEngine: () => localize('statusBar.restartEngine', 'Reiniciar motor'),
    restartEngineDetail: () => localize('statusBar.restartEngineDetail', 'Reinicia o servidor LSP e limpa o cache'),
    engineRestarted: () => localize('statusBar.engineRestarted', 'PawnPro: motor reiniciado.'),
    configNotFound: () => localize('statusBar.configNotFound', 'Nenhum workspace aberto.'),
    sectionServer: () => localize('statusBar.sectionServer', 'Servidor'),
    serverStart: () => localize('statusBar.serverStart', 'Iniciar servidor'),
    serverStop: () => localize('statusBar.serverStop', 'Parar servidor'),
    serverRestart: () => localize('statusBar.serverRestart', 'Reiniciar servidor'),
    editServerCfg: () => localize('statusBar.editServerCfg', 'Editar configuração do servidor'),
    editServerCfgDetail: () => localize('statusBar.editServerCfgDetail', 'Abre server.cfg (SA-MP) ou config.json (open.mp)'),
    serverCfgNotFound: (p: string) => localize('statusBar.serverCfgNotFound', 'Arquivo de configuração não encontrado em: {0}', p),
    sectionTemplates: () => localize('statusBar.sectionTemplates', 'Novo script'),
    newGamemode: () => localize('statusBar.newGamemode', 'Novo Gamemode'),
    newFilterscript: () => localize('statusBar.newFilterscript', 'Novo Filterscript'),
    newInclude: () => localize('statusBar.newInclude', 'Novo Include'),
  },

  whatsNew: {
    panelTitle:   () => localize('whatsNew.panelTitle', 'PawnPro — O que há de novo'),
    noChangelog:  () => localize('whatsNew.noChangelog', 'Nenhum registro de mudanças encontrado para esta versão.'),
    reopenHint:   () => localize('whatsNew.reopenHint', 'Use <code>PawnPro: O que há de novo</code> para reabrir.'),
  },

  templates: {
    selectVariant:    () => localize('templates.selectVariant', 'Selecione a variante'),
    selectType:       () => localize('templates.selectType', 'Selecione o tipo de script'),
    labelGmOmp:       () => localize('templates.label.gmOmp', 'Gamemode — open.mp'),
    labelGmSamp:      () => localize('templates.label.gmSamp', 'Gamemode — SA-MP'),
    labelFsOmp:       () => localize('templates.label.fsOmp', 'Filterscript — open.mp'),
    labelFsSamp:      () => localize('templates.label.fsSamp', 'Filterscript — SA-MP'),
    labelIncOmp:      () => localize('templates.label.incOmp', 'Include — open.mp'),
    descGmOmp:        () => localize('templates.desc.gmOmp', '#include <open.mp>'),
    descGmSamp:       () => localize('templates.desc.gmSamp', '#include <a_samp>'),
    descFsOmp:        () => localize('templates.desc.fsOmp', '#include <open.mp>'),
    descFsSamp:       () => localize('templates.desc.fsSamp', '#include <a_samp>'),
    descIncOmp:       () => localize('templates.desc.incOmp', '.inc para open.mp'),
  },
};
